name: shadow_deals
description: "Erlebe ein strategisches Spielerlebnis, bei dem Entscheidungen über Profit und Verlust bestimmen. Schließe Deals, handle geschickt und finde deinen Weg in der Unterwelt. Jede Runde birgt neue Chancen – die Wahl liegt bei dir."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  dio: ^5.7.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  universal_io: ^2.2.2
  flutter_markdown: ^0.7.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/markdown/
    - assets/credentials.json
