name: Build Flutter

on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: "Set Flutter 3.10.6"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
      - name: "Checkout Flutter 3.10.7"
        shell: bash
        run: |
          cd $FLUTTER_ROOT;
          git fetch --tags;
          git checkout 3.10.7;
          flutter --version;
      - name: Build Flutter Web Release
        run: flutter build web --release
